# directory for the project; we don't really touch this
projdir: /mnt/isilon/microbiome/Hiseq01/XX/Data/Intensities/BaseCalls    
# todo: transfer from isilon to lustre; gunzip; merge; 

admins: zhaocy.dut@gmail.com      # to receive notification of success or fail
tmpdir: /mnt/lustre/users/zhaoc1/test   # for some tools to create temporary files

load_environment: source activate dnabc

# customized settings for a project ---- START
data_dir: "/home/zhaoc1/dnabc_sunbeam/tests"
lane_num: "001"
barcodes: "barcodes.txt"
threads: 1
# customized settings for a project ---- DONE

# subdirectories in data_dir
output:
    dnabc: dnabc_results

