# directory for the incoming data: we never touch this!
incoming_dir: /mnt/isilon/microbiome/incoming    
flowcell_id: 180123_D00728_0055_ACC6PUANXX
lane_num: "45"
 

# to receive notification of success or fail
admins: zhaocy.dut@gmail.com
tmpdir: /mnt/lustre/users/zhaoc1/test   # for some tools to create temporary files

load_environment: source activate dnabc

project_dir: "/home/zhaoc1/dnabc_sunbeam/tests"
barcodes: "barcodes.txt"
threads: 1

# subdirectories in project
output:
    dnabc: dnabc_results

